#!/usr/bin/env python3
"""Generate diagnostic API tokens and SHA-256 hashes without writing files."""

from __future__ import annotations

import argparse
import hashlib
import secrets
import sys
from collections.abc import Sequence
from typing import TextIO

DEFAULT_TOKEN_BYTES = 32
MIN_TOKEN_BYTES = 16


def generate_token(byte_length: int = DEFAULT_TOKEN_BYTES) -> str:
    """Return a URL-safe token with a minimum entropy floor."""
    if byte_length < MIN_TOKEN_BYTES:
        raise ValueError(f"token byte length must be at least {MIN_TOKEN_BYTES}")
    return secrets.token_urlsafe(byte_length)


def hash_token(token: str) -> str:
    """Return the SHA-256 hex digest expected by DIAG_ACCESS_TOKEN_SHA256."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a diagnostic token or derive DIAG_ACCESS_TOKEN_SHA256. "
            "The script never writes token files."
        )
    )
    parser.add_argument(
        "--bytes",
        type=int,
        default=DEFAULT_TOKEN_BYTES,
        help=f"random byte length for generated tokens, minimum {MIN_TOKEN_BYTES}",
    )

    input_group = parser.add_mutually_exclusive_group()
    input_group.add_argument(
        "--stdin",
        action="store_true",
        help="read an existing token from standard input before hashing it",
    )

    output_group = parser.add_mutually_exclusive_group()
    output_group.add_argument(
        "--token-only",
        action="store_true",
        help="print only a newly generated clear token for shell capture",
    )
    output_group.add_argument(
        "--hash-only",
        action="store_true",
        help="print only the SHA-256 token hash",
    )
    return parser


def resolve_token(args: argparse.Namespace, stdin: TextIO) -> tuple[str, bool]:
    """Return the token and whether it was generated by this invocation."""
    if args.stdin:
        token = stdin.read().strip()
        if not token:
            raise ValueError("no token received on stdin")
        return token, False
    return generate_token(args.bytes), True


def main(
    argv: Sequence[str] | None = None,
    stdin: TextIO = sys.stdin,
    stdout: TextIO = sys.stdout,
    stderr: TextIO = sys.stderr,
) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        token, generated = resolve_token(args, stdin)
    except ValueError as exc:
        print(f"error: {exc}", file=stderr)
        return 2

    token_hash = hash_token(token)

    if args.token_only:
        if not generated:
            print("error: --token-only requires a generated token", file=stderr)
            return 2
        print(token, file=stdout)
    elif args.hash_only:
        print(token_hash, file=stdout)
    else:
        print(f"DIAG_ACCESS_TOKEN_SHA256={token_hash}", file=stdout)
        if generated:
            print(
                "# Clear token intentionally not printed; use --token-only in a "
                "shell variable when you need a new client token.",
                file=stdout,
            )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
